{
 "title": "Monitoring - Perfmon Counters - Quest Softwares",
 "description": "This dashboard is designed to match the counters mentioned in document published by QUEST SOFTWARE on \"SQL Server Perfmon Counters of Interest\"",
 "tags": [
  "SqlServer",
  "MSSQL",
  "Performance-Counter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "select server_name\nfrom (values ('MSI')\n\t\t\t,('SQL-A')\n\t\t\t,('SQL-A\\V17')\n\t ) as servers (server_name);"
   }
  ]
 },
 "panels": [
  {
   "title": "OS Memory & Paging Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Available Mbytes",
     "type": "graph",
     "description": "Unused physical memory (not page file).\nShould be greater than 2 GB",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT l2u.utc_time as time, (available_physical_memory_kb*1.0)/1024 as [Available Memory]\nFROM (\n\t\tselect collection_time, available_physical_memory_kb\n\t\tfrom [dbo].[dm_os_sys_memory]\n\t\twhere collection_time BETWEEN @p_start_time AND @p_end_time\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect collection_time, available_physical_memory_kb\n\t\tfrom [dbo].[dm_os_sys_memory_aggregated]\n\t\twhere collection_time BETWEEN @p_start_time AND @p_end_time\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Memory - Pages Input/Sec, Pages/Sec",
     "type": "graph",
     "description": "Pages Input/Sec\n-- Should be less than 10\n-- Reads from hard disk per second to resolve\nhard pages.\n\nPages/Sec\nOften referenced in older documentation.\nUseful only in combination with Pages\nInput/Sec, %Usage, %Usage Peak.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT l2u.utc_time as time,counter_name, CEILING(cntr_value) as cntr_value\nFROM (\n\t\tselect pc.collection_time, pc.counter_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] = 'Memory'\n\t\t\tand pc.counter_name in ('Pages Input/Sec','Pages/Sec')\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect pc.collection_time, pc.counter_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] = 'Memory'\n\t\t\tand pc.counter_name in ('Pages Input/Sec','Pages/Sec')\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Paging File Usage",
     "type": "graph",
     "description": "Paging File: %Usage\n-- Should be less than 70%\n-- Amount of Page File in use, which indicates\nthe server is substituting disk space for\nmemory.\n\nPaging File: %Usage Peak\n-- Should be less than 70%\n-- Highest %Usage metric since the last time\nthe server was restarted.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT l2u.utc_time as time, counter_name, CEILING(cntr_value) as cntr_value\nFROM (\n\t\tselect collection_time, pc.counter_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] = 'Paging File'\n\t\t\tand pc.counter_name in ('% Usage','% Usage Peak')\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect collection_time, pc.counter_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] = 'Paging File'\n\t\t\tand pc.counter_name in ('% Usage','% Usage Peak')\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "OS CPU & Processor Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "%Processor Time (SqlServer)",
     "type": "graph",
     "description": "< 80%. \nPercentage of processor time spent on SQL\nServer process threads.You may also wish\nto investigate other Process (sqlservr) such\nas Private Bytes, Virtual Bytes, Working Set,\netc to get a fuller understanding of how\nSQL Server allocates certain segments of\nmemory. Usually, these auxiliary counters\nprovide contextual information and are not\nnecessary for troubleshooting.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT  /* Grafana => CPU */\n\t\tl2u.utc_time as time,\n\t\tmetric COLLATE SQL_Latin1_General_CP1_CI_AS,\n\t\t[value]\nFROM (\n\t\tselect collection_time, metric, [value]\n\t\tfrom (\tselect\tcollection_time,\n\t\t\t\t\t\tsystem_cpu_utilization as [% Processor Time (os)],\n\t\t\t\t\t\tsql_cpu_utilization as [% Processor Time (sqlservr)]\n\t\t\t\tfrom dbo.dm_os_ring_buffers\n\t\t\t\twhere collection_time BETWEEN @p_start_time AND @p_end_time\n\t\t\t ) as up\n\t\tUNPIVOT ([value] FOR metric IN ([% Processor Time (os)],[% Processor Time (sqlservr)])) AS UnPvt\n\t\t--\n\t\tUNION ALL\n\t\t--\n\t\tselect collection_time, metric, [value]\n\t\tfrom (\tselect\tcollection_time,\n\t\t\t\t\t\tsystem_cpu_utilization as [% Processor Time (os)],\n\t\t\t\t\t\tsql_cpu_utilization as [% Processor Time (sqlservr)]\n\t\t\t\tfrom dbo.dm_os_ring_buffers_aggregated\n\t\t\t\twhere collection_time BETWEEN @p_start_time AND @p_end_time\n\t\t\t ) as up\n\t\tUNPIVOT ([value] FOR metric IN ([% Processor Time (os)],[% Processor Time (sqlservr)])) AS UnPvt\n\t\t--\n\t\tUNION ALL\n\t\t--\n\t\tselect  collection_time\n\t\t\t\t,metric = case when pc.[object_name] = 'Process' then counter_name + ' ('+pc.instance_name+')'\n\t\t\t\t\t\t\t\twhen  pc.[object_name] = 'Processor' then counter_name + ' ('+pc.[object_name]+')'\n\t\t\t\t\t\t\telse null\n\t\t\t\t\t\t\tend  COLLATE SQL_Latin1_General_CP1_CI_AS\n\t\t\t\t,[value] = pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc with (nolock)\n\t\twhere collection_time BETWEEN @p_start_time AND @p_end_time\n\t\tand\t(\t(pc.[object_name] = 'Processor' and counter_name = '% Privileged Time')\n\t\t\t)\n\t\t--\n\t\tUNION ALL\n\t\t--\n\t\tselect  collection_time\n\t\t\t\t,metric = case when pc.[object_name] = 'Process' then counter_name + ' ('+pc.instance_name+')'\n\t\t\t\t\t\t\t\twhen  pc.[object_name] = 'Processor' then counter_name + ' ('+pc.[object_name]+')'\n\t\t\t\t\t\t\telse null\n\t\t\t\t\t\t\tend  COLLATE SQL_Latin1_General_CP1_CI_AS\n\t\t\t\t,[value] = pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc with (nolock)\n\t\twhere collection_time BETWEEN @p_start_time AND @p_end_time\n\t\tand\t(\t(pc.[object_name] = 'Processor' and counter_name = '% Privileged Time')\n\t\t\t)\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Per cpu - Processor Queue Length",
     "type": "graph",
     "description": "Number of threads waiting for CPU cycles,\nwhere < 12 per CPU is good/fair, < 8 is better,\n< 4 is best.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT  l2u.utc_time as time\n\t\t,metric = 'CPU - '+counter_name+' ('+[object_name]+')'\n\t\t,[value] = cntr_value/cpu_count\nFROM (\n\t\tselect  pc.collection_time ,pc.counter_name ,pc.[object_name] ,pc.cntr_value ,si.cpu_count\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc with (nolock)\n\t\touter apply ( select top 1 cpu_count from dbo.dm_os_sys_info as si where si.collection_time <= pc.collection_time) as si\n\t\twhere\t(\tcollection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand\t(\t(pc.[object_name] = 'System' and counter_name = 'Processor Queue Length')\n\t\t\t\t\t--or\n\t\t\t\t\t--(pc.[object_name] = 'System' and counter_name = 'Context Switches/sec')\n\t\t\t\t)\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect  pc.collection_time ,pc.counter_name ,pc.[object_name] ,pc.cntr_value ,si.cpu_count\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc with (nolock)\n\t\touter apply ( select top 1 cpu_count from dbo.dm_os_sys_info as si where si.collection_time <= pc.collection_time) as si\n\t\twhere\t(\tcollection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand\t(\t(pc.[object_name] = 'System' and counter_name = 'Processor Queue Length')\n\t\t\t\t\t--or\n\t\t\t\t\t--(pc.[object_name] = 'System' and counter_name = 'Context Switches/sec')\n\t\t\t\t)\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Data Access Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Access Methods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name, cntr_value\r\nFROM (\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere (collection_time BETWEEN @p_start_time AND @p_end_time) \r\n\t\t\tand pc.object_name = (@object_name+':Access Methods')\r\n\t\t\tand pc.counter_name not in ('Index Searches/sec')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere (collection_time BETWEEN @p_start_time AND @p_end_time) \r\n\t\t\tand pc.object_name = (@object_name+':Access Methods')\r\n\t\t\tand pc.counter_name not in ('Index Searches/sec')\r\n) AS data\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Access Methods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name, cntr_value\r\nFROM (\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere (collection_time BETWEEN @p_start_time AND @p_end_time) \r\n\t\t\tand pc.object_name = (@object_name+':Access Methods')\r\n\t\t\tand pc.counter_name in ('Index Searches/sec')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere (collection_time BETWEEN @p_start_time AND @p_end_time) \r\n\t\t\tand pc.object_name = (@object_name+':Access Methods')\r\n\t\t\tand pc.counter_name in ('Index Searches/sec')\r\n) AS data\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Server: Memory Manager Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Server: Memory Manager",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\ndeclare @object_name varchar(255);\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT  l2u.utc_time as time, \n\t\tmetric = counter_name,\n\t\t[value] = cntr_value\nFROM (\n\t\tselect\tcollection_time, pc.counter_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\tand (\t(pc.[object_name] = (@object_name+':Memory Manager')\n\t\t\t\tand pc.counter_name in ('Granted Workspace Memory (KB)','Maximum Workspace Memory (KB)','Target Server Memory (KB)'))\n\t\t\t)\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect\tcollection_time, pc.counter_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\tand (\t(pc.[object_name] = (@object_name+':Memory Manager')\n\t\t\t\tand pc.counter_name in ('Granted Workspace Memory (KB)','Maximum Workspace Memory (KB)','Target Server Memory (KB)'))\n\t\t\t)\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Memory Grants",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\ndeclare @object_name varchar(255);\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\n\t\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT\tl2u.utc_time as time,\n\t\tmetric = counter_name,\n\t\t[value] = cntr_value\nFROM (\n\t\tselect\tcollection_time, counter_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\tand (\t(pc.[object_name] = (@object_name+':Memory Manager') and pc.counter_name in ('Memory Grants Outstanding','Memory Grants Pending'))\n\t\t\t)\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect\tcollection_time, counter_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\tand (\t(pc.[object_name] = (@object_name+':Memory Manager') and pc.counter_name in ('Memory Grants Outstanding','Memory Grants Pending'))\n\t\t\t)\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logical Disk - Queue Length",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT\t/* Load on Disk */\n\t\ttime = l2u.utc_time,\n\t\tmetric = counter_name+' ('+instance_name+')',\n\t\t[value] = cntr_value\nFROM (\n\t\tselect  collection_time, counter_name, instance_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'LogicalDisk' )\n\t\t\tand pc.counter_name in ('Current Disk Queue Length')\n\t\t\tand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect  collection_time, counter_name, instance_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'LogicalDisk' )\n\t\t\tand pc.counter_name in ('Current Disk Queue Length')\n\t\t\tand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Logical Disk - Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT\tl2u.utc_time as time,\n\t\tmetric = counter_name+' ('+instance_name+')',\n\t\t[value] = cntr_value\nFROM (\n\t\tselect collection_time, counter_name, instance_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'LogicalDisk' )\n\t\t\t--and pc.[object_name] in ( 'PhysicalDisk' )\n\t\t\tand pc.counter_name in ('Avg. Disk sec/Read','Avg. Disk sec/Write')\n\t\t\tand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect collection_time, counter_name, instance_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'LogicalDisk' )\n\t\t\t--and pc.[object_name] in ( 'PhysicalDisk' )\n\t\t\tand pc.counter_name in ('Avg. Disk sec/Read','Avg. Disk sec/Write')\n\t\t\tand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Logical Disk - Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT\t/* Load on Disk */\n\t\t[time] = l2u.utc_time,\n\t\tmetric = counter_name+' ('+instance_name+')',\n\t\t[value] = cntr_value\nFROM (\n\t\tselect  pc.collection_time, counter_name, pc.instance_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'LogicalDisk' )\n\t\t\tand pc.counter_name in ('Disk Bytes/sec','Disk Write Bytes/sec','Disk Read Bytes/sec')\n\t\t\tand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect  pc.collection_time, counter_name, pc.instance_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'LogicalDisk' )\n\t\t\tand pc.counter_name in ('Disk Bytes/sec','Disk Write Bytes/sec','Disk Read Bytes/sec')\n\t\t\tand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Physical Disk - Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT\t[time] = l2u.utc_time,\n\t\tmetric = counter_name+' ('+instance_name+')',\n\t\t[value] = cntr_value\nFROM (\n\t\tselect pc.collection_time, counter_name, pc.instance_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'PhysicalDisk' )\n\t\t\tand pc.counter_name in ('Avg. Disk sec/Read','Avg. Disk sec/Write')\n\t\t\tand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect pc.collection_time, counter_name, pc.instance_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'PhysicalDisk' )\n\t\t\tand pc.counter_name in ('Avg. Disk sec/Read','Avg. Disk sec/Write')\n\t\t\tand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Interface - Bytes Total/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT\t/* Load on Disk */\n\t\t[time] = l2u.utc_time,\n\t\tmetric = instance_name,\n\t\t[value] = cntr_value\nFROM (\n\t\tselect  pc.collection_time, pc.instance_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'Network Interface' )\n\t\t\tand pc.counter_name in ('Bytes Total/sec')\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect  pc.collection_time, pc.instance_name, pc.cntr_value\n\t\tfrom dbo.dm_os_performance_counters_nonsql_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.[object_name] in ( 'Network Interface' )\n\t\t\tand pc.counter_name in ('Bytes Total/sec')\n) AS data\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL User Database Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Databases - Log File Usage ( > 1GB)",
     "type": "graph",
     "description": "Monitor these counters to determine general benchmark levels set by your user databases and for tempdb.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\ndeclare @object_name varchar(255);\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\n;WITH T_Dbs AS (\n\tselect *\n\tfrom dbo.dm_os_performance_counters as pc\n\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\tand pc.[object_name] = (@object_name+':Databases')\n\t\tand pc.counter_name in ('Log File(s) Used Size (KB)','Log File(s) Size (KB)')\n\t\tand instance_name not in ('_Total','master','model','mssqlsystemresource')\n\t--\n\tunion all\n\t--\n\tselect *\n\tfrom dbo.dm_os_performance_counters_aggregated as pc\n\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\tand pc.[object_name] = (@object_name+':Databases')\n\t\tand pc.counter_name in ('Log File(s) Used Size (KB)','Log File(s) Size (KB)')\n\t\tand instance_name not in ('_Total','master','model','mssqlsystemresource')\n)\nselect [time] = l2u.utc_time,\n\t\tmetric = case when counter_name = 'Log File(s) Size (KB)' then 'Total Size (KB) - '+QUOTENAME(pc.instance_name)\n\t\t\t\t\t\twhen counter_name = 'Log File(s) Used Size (KB)' then 'Used Size (KB) - '+QUOTENAME(pc.instance_name)\n\t\t\t\t\t\telse counter_name+' ('+pc.instance_name+')'\n\t\t\t\t\t\tend ,\n\t\t[value] = pc.cntr_value\nfrom T_Dbs as pc\ncross apply dbo.local2utc(collection_time) as l2u\nwhere pc.instance_name in (\tselect i.instance_name \n\t\t\t\t\t\t\tfrom T_Dbs as i \n\t\t\t\t\t\t\twhere i.counter_name = 'Log File(s) Size (KB)'\n\t\t\t\t\t\t\t\tand i.cntr_value/(1024.0*1024) > 1.0\n\t\t\t\t\t\t)\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Server SQL Statistics Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:SQL Statistics",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name, cntr_value\r\nFROM (\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':SQL Statistics') --and counter_name not in ('Memory Grants Pending')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':SQL Statistics') --and counter_name not in ('Memory Grants Pending')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Buffer Manager & Memory Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name, cntr_value\r\nFROM (\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Buffer Manager') and counter_name in ('Page lookups/sec','Page reads/sec','Page writes/sec','Readahead pages/sec')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Buffer Manager') and counter_name in ('Page lookups/sec','Page reads/sec','Page writes/sec','Readahead pages/sec')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name, cntr_value\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Buffer Manager') and counter_name not in ('Page life expectancy','Database pages','Target pages')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Buffer Manager') and counter_name not in ('Page life expectancy','Database pages','Target pages')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL “How is My Memory Being Used” Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Memory Manager')\r\n\t\t\tand counter_name in ('Total Server Memory (KB)','Target Server Memory (KB)')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Memory Manager')\r\n\t\t\tand counter_name in ('Total Server Memory (KB)','Target Server Memory (KB)')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Memory Manager')\r\n\t\t\tand counter_name in ('Stolen Server Memory (KB)','SQL Cache Memory (KB)','Free Memory (KB)')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Memory Manager')\r\n\t\t\tand counter_name in ('Stolen Server Memory (KB)','SQL Cache Memory (KB)','Free Memory (KB)')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Workload Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:SQL Statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\ndeclare @p_start_time datetime2;\ndeclare @p_end_time datetime2;\ndeclare @object_name varchar(255);\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\n\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\n\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\nFROM (\t\n\t\tselect collection_time, counter_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.object_name = (@object_name+':SQL Statistics')\n\t\t\tand counter_name in ('Batch Requests/sec','SQL Compilations/sec','SQL Re-Compilations/sec','SQL Attention rate')\n\t\t--\n\t\tunion all\n\t\t--\n\t\tselect collection_time, counter_name, cntr_value\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\n\t\t\tand pc.object_name = (@object_name+':SQL Statistics')\n\t\t\tand counter_name in ('Batch Requests/sec','SQL Compilations/sec','SQL Re-Compilations/sec','SQL Attention rate')\n) AS pc\ncross apply dbo.local2utc(collection_time) as l2u\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Number of Deadlocks/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, instance_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, instance_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Locks')\r\n\t\t\tand pc.counter_name = 'Number of Deadlocks/sec'\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, instance_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Locks')\r\n\t\t\tand pc.counter_name = 'Number of Deadlocks/sec'\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:SQL Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, instance_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, instance_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':SQL Errors')\r\n\t\t\tand pc.instance_name <> '_Total'\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, instance_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':SQL Errors')\r\n\t\t\tand pc.instance_name <> '_Total'\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQLServer:Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Longest Transaction Running Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Transactions')\r\n\t\t\tand pc.counter_name in ('Longest Transaction Running Time')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Transactions')\r\n\t\t\tand pc.counter_name in ('Longest Transaction Running Time')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "Free Space in tempdb (KB)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Transactions')\r\n\t\t\tand pc.counter_name in ('Free Space in tempdb (KB)')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Transactions')\r\n\t\t\tand pc.counter_name in ('Free Space in tempdb (KB)')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Transactions')\r\n\t\t\tand pc.counter_name in ('Transactions')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Transactions')\r\n\t\t\tand pc.counter_name in ('Transactions')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "Version Store Size (KB)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Transactions')\r\n\t\t\tand pc.counter_name in ('Version Store Size (KB)')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Transactions')\r\n\t\t\tand pc.counter_name in ('Version Store Size (KB)')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQLServer:General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:General Statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand (\tpc.object_name = (@object_name+':General Statistics')\r\n\t\t\t\t\tand\t\r\n\t\t\t\t\t(\tpc.counter_name in ('User Connections','Logins/sec','Logouts/sec') )\r\n\t\t\t\t)\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand (\tpc.object_name = (@object_name+':General Statistics')\r\n\t\t\t\t\tand\t\r\n\t\t\t\t\t(\tpc.counter_name in ('User Connections','Logins/sec','Logouts/sec') )\r\n\t\t\t\t)\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Users & Locks Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Latches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Latches')\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Latches')\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Locks -> Lock Waits/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, counter_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Locks')\r\n\t\t\tand pc.counter_name = 'Lock Waits/sec'\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, counter_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Locks')\r\n\t\t\tand pc.counter_name = 'Lock Waits/sec'\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Locks - Average Wait Time (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, instance_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, instance_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Locks')\r\n\t\t\tand pc.counter_name = 'Average Wait Time (ms)'\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, instance_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Locks')\r\n\t\t\tand pc.counter_name = 'Average Wait Time (ms)'\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Locks - Lock Wait Time (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\ndeclare @p_start_time datetime2;\r\ndeclare @p_end_time datetime2;\r\ndeclare @object_name varchar(255);\r\nset @object_name = (case when @@SERVICENAME = 'MSSQLSERVER' then 'SQLServer' else 'MSSQL$'+@@SERVICENAME end);\r\n\r\nselect @p_start_time = st.local_time, @p_end_time = et.local_time \r\nfrom dbo.utc2local($__timeFrom()) as st join dbo.utc2local($__timeTo()) et on 1 = 1;\r\n\r\nSELECT l2u.utc_time as time, instance_name as metric, cntr_value as [value]\r\nFROM (\t\r\n\t\tselect collection_time, instance_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Locks')\r\n\t\t\tand pc.counter_name = 'Lock Wait Time (ms)'\r\n\t\t--\r\n\t\tunion all\r\n\t\t--\r\n\t\tselect collection_time, instance_name, cntr_value\r\n\t\tfrom dbo.dm_os_performance_counters_aggregated as pc\r\n\t\twhere ( collection_time BETWEEN @p_start_time AND @p_end_time )\r\n\t\t\tand pc.object_name = (@object_name+':Locks')\r\n\t\t\tand pc.counter_name = 'Lock Wait Time (ms)'\r\n) AS pc\r\ncross apply dbo.local2utc(collection_time) as l2u\r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  }
 ]
}